require('dotenv').config();
const http = require('http');
const crypto = require('crypto');

const port = process.env.PORT || 3000;
const secret = process.env.WEBHOOK_SECRET || 'test_secret_key';

// Mock values
const paymentId = 'pay_' + Math.random().toString(36).substring(2, 12).toUpperCase();
const randomAmount = Math.floor(Math.random() * (10000 - 100 + 1)) + 100; // Between 1.00 INR and 100.00 INR

// Payload structure matching Razorpay payload specifications
const payload = {
  entity: 'event',
  account_id: 'acc_NpBqU6ZfL3fV0u',
  event: 'payment.captured',
  contains: ['payment'],
  payload: {
    payment: {
      entity: {
        id: paymentId,
        entity: 'payment',
        amount: randomAmount, // in paise
        currency: 'INR',
        status: 'captured',
        order_id: 'order_MockOrder123',
        invoice_id: null,
        international: false,
        method: 'upi',
        amount_refunded: 0,
        refund_status: null,
        captured: true,
        description: 'Mock transaction generated by simulator',
        card_id: null,
        bank: null,
        wallet: null,
        vpa: 'success@razorpay',
        email: 'mudassirs472@gmail.com',
        contact: '+919958399157',
        notes: {
          'enter you company name': 'Infiplus Technologies'
        },
        fee: Math.round(randomAmount * 0.02),
        tax: 0,
        error_code: null,
        error_description: null,
        created_at: Math.floor(Date.now() / 1000)
      }
    }
  },
  created_at: Math.floor(Date.now() / 1000)
};

const payloadString = JSON.stringify(payload);

// Calculate expected signature using target secret
const signature = crypto
  .createHmac('sha256', secret)
  .update(payloadString)
  .digest('hex');

console.log('--- Simulating Webhook POST Request ---');
console.log(`Target URL: http://localhost:${port}/webhook`);
console.log(`Payment ID: ${paymentId}`);
console.log(`Amount: ₹${(randomAmount / 100).toFixed(2)}`);
console.log(`Computed Signature: ${signature}`);

// Set up node HTTP options
const options = {
  hostname: 'localhost',
  port: port,
  path: '/webhook',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'x-razorpay-signature': signature,
    'Content-Length': Buffer.byteLength(payloadString)
  }
};

const req = http.request(options, (res) => {
  let body = '';
  res.setEncoding('utf8');
  res.on('data', (chunk) => {
    body += chunk;
  });
  res.on('end', () => {
    console.log(`Response Status Code: ${res.statusCode}`);
    console.log(`Response Body: ${body}`);
    console.log('---------------------------------------');
  });
});

req.on('error', (e) => {
  console.error(`Request failed: ${e.message}`);
  console.log('Is the node server running? Run `npm start` first.');
});

// Write data to request body
req.write(payloadString);
req.end();
